import { useEffect, useMemo, useState } from "react";
import { Link, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import {
  Activity,
  BarChart3,
  Bell,
  CheckCircle2,
  ChevronRight,
  Clock3,
  Gauge,
  GitCompare,
  History,
  LayoutDashboard,
  Menu,
  Moon,
  Network,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Sun,
  Terminal,
  X,
  Zap
} from "lucide-react";
import { createAnalysis, getAnalyses, getHealth } from "./api";
import type { Analysis } from "./types";
import { formatDate, scoreLabel, severityClass } from "./utils";

const navItems = [
  { to: "/", label: "Overview", icon: LayoutDashboard },
  { to: "/analyze", label: "New Analysis", icon: Search },
  { to: "/history", label: "History", icon: History },
  { to: "/compare", label: "Compare", icon: GitCompare },
  { to: "/architecture", label: "Architecture", icon: Network }
];

function App() {
  const [dark, setDark] = useState(() => localStorage.getItem("fpd-theme") === "dark");
  const [mobileOpen, setMobileOpen] = useState(false);

  useEffect(() => {
    document.documentElement.dataset.theme = dark ? "dark" : "light";
    localStorage.setItem("fpd-theme", dark ? "dark" : "light");
  }, [dark]);

  return (
    <div className="app-shell">
      <aside className={`sidebar ${mobileOpen ? "mobile-open" : ""}`}>
        <div className="brand">
          <div className="brand-mark"><Gauge size={20} /></div>
          <div>
            <strong>PerfDoctor</strong>
            <span>Frontend Intelligence</span>
          </div>
          <button className="icon-btn mobile-close" onClick={() => setMobileOpen(false)} aria-label="Close menu">
            <X size={18} />
          </button>
        </div>

        <nav className="nav">
          <div className="nav-label">WORKSPACE</div>
          {navItems.map(({ to, label, icon: Icon }) => (
            <NavItem key={to} to={to} label={label} icon={<Icon size={18} />} />
          ))}
          <div className="nav-label nav-gap">SYSTEM</div>
          <NavItem to="/settings" label="Settings" icon={<Settings size={18} />} />
        </nav>

        <div className="sidebar-card">
          <Sparkles size={18} />
          <strong>Demo analysis mode</strong>
          <p>Metrics are generated by a deterministic local analysis engine for portfolio/demo use.</p>
        </div>
      </aside>

      <main className="main">
        <header className="topbar">
          <button className="icon-btn mobile-menu" onClick={() => setMobileOpen(true)} aria-label="Open menu">
            <Menu size={20} />
          </button>
          <div className="breadcrumb">Developer Tools <ChevronRight size={15} /> Performance</div>
          <div className="topbar-actions">
            <span className="live-dot"><span /> Demo Engine Online</span>
            <button className="icon-btn" onClick={() => setDark(!dark)} aria-label="Toggle theme">
              {dark ? <Sun size={18} /> : <Moon size={18} />}
            </button>
          </div>
        </header>

        <Routes>
          <Route path="/" element={<Overview />} />
          <Route path="/analyze" element={<Analyze />} />
          <Route path="/history" element={<HistoryPage />} />
          <Route path="/compare" element={<ComparePage />} />
          <Route path="/architecture" element={<Architecture />} />
          <Route path="/settings" element={<SettingsPage />} />
          <Route path="*" element={<NotFound />} />
        </Routes>
      </main>
    </div>
  );
}

function NavItem({ to, label, icon }: { to: string; label: string; icon: React.ReactNode }) {
  const location = useLocation();
  const active = location.pathname === to;
  return (
    <Link className={`nav-item ${active ? "active" : ""}`} to={to}>
      {icon}<span>{label}</span>
    </Link>
  );
}

function PageHeader({ eyebrow, title, description, action }: {
  eyebrow: string; title: string; description: string; action?: React.ReactNode;
}) {
  return (
    <div className="page-header">
      <div>
        <div className="eyebrow">{eyebrow}</div>
        <h1>{title}</h1>
        <p>{description}</p>
      </div>
      {action}
    </div>
  );
}

function Overview() {
  const [analyses, setAnalyses] = useState<Analysis[]>([]);
  const [health, setHealth] = useState("checking");

  useEffect(() => {
    getAnalyses().then(setAnalyses).catch(() => setAnalyses([]));
    getHealth().then(() => setHealth("healthy")).catch(() => setHealth("offline"));
  }, []);

  const latest = analyses[0];
  const average = analyses.length
    ? Math.round(analyses.reduce((sum, a) => sum + a.performanceScore, 0) / analyses.length)
    : 0;

  return (
    <div className="page">
      <PageHeader
        eyebrow="Performance workspace"
        title="Frontend Performance Doctor"
        description="Analyze loading, network, asset and rendering signals with an explainable performance engine."
        action={<Link className="primary-btn" to="/analyze"><Zap size={17} /> Analyze website</Link>}
      />

      <div className="hero-banner">
        <div>
          <div className="pill"><Activity size={14} /> Developer tool</div>
          <h2>Find bottlenecks before users feel them.</h2>
          <p>Run a demo analysis, inspect the evidence, and compare performance improvements over time.</p>
        </div>
        <div className="hero-icon"><Terminal size={34} /></div>
      </div>

      <div className="stat-grid">
        <StatCard icon={<Gauge />} label="Latest score" value={latest ? `${latest.performanceScore}/100` : "—"} meta={latest ? scoreLabel(latest.performanceScore) : "Run an analysis"} />
        <StatCard icon={<Clock3 />} label="Avg. LCP" value={latest ? `${latest.lcp.toFixed(1)}s` : "—"} meta="Largest Contentful Paint" />
        <StatCard icon={<Network />} label="Avg. API" value={latest ? `${latest.apiResponseTime}ms` : "—"} meta="Latest analysis" />
        <StatCard icon={<History />} label="Analyses" value={String(analyses.length)} meta={`Average score ${average || "—"}`} />
      </div>

      <div className="two-col">
        <section className="panel">
          <div className="panel-head">
            <div><h3>Recent analyses</h3><span>Latest performance reports</span></div>
            <Link to="/history" className="text-link">View all <ChevronRight size={15} /></Link>
          </div>
          {analyses.length === 0 ? (
            <EmptyState />
          ) : (
            <div className="table-wrap">
              <table>
                <thead><tr><th>URL</th><th>Score</th><th>LCP</th><th>Created</th></tr></thead>
                <tbody>
                  {analyses.slice(0, 5).map((a) => (
                    <tr key={a.id}>
                      <td><strong>{a.url}</strong><small>Demo analysis</small></td>
                      <td><ScoreBadge score={a.performanceScore} /></td>
                      <td>{a.lcp.toFixed(1)}s</td>
                      <td>{formatDate(a.createdAt)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </section>

        <section className="panel">
          <div className="panel-head">
            <div><h3>System status</h3><span>Local development services</span></div>
          </div>
          <div className="status-list">
            <StatusRow label="Frontend" status="Online" ok />
            <StatusRow label="REST API" status={health === "healthy" ? "Online" : health === "offline" ? "Offline" : "Checking"} ok={health === "healthy"} />
            <StatusRow label="Analysis engine" status="Ready" ok />
            <StatusRow label="Demo dataset" status="Loaded" ok />
          </div>
          <div className="note-box"><ShieldCheck size={18} /><span>All demo metrics are generated transparently by deterministic rules. No external site is crawled.</span></div>
        </section>
      </div>
    </div>
  );
}

function Analyze() {
  const [url, setUrl] = useState("https://demo.example.com");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [analysis, setAnalysis] = useState<Analysis | null>(null);

  async function handleAnalyze(e: React.FormEvent) {
    e.preventDefault();
    setError("");
    setAnalysis(null);
    setLoading(true);
    try {
      const result = await createAnalysis(url.trim());
      setAnalysis(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Analysis failed");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="page">
      <PageHeader
        eyebrow="New report"
        title="Analyze a website"
        description="Enter a URL to generate a deterministic demo performance report."
      />

      <section className="panel analyze-form">
        <div className="form-icon"><Search size={22} /></div>
        <div className="form-copy">
          <h3>Start a performance analysis</h3>
          <p>Demo mode creates consistent metrics from the URL. This keeps the project reliable during local demos and interviews.</p>
        </div>
        <form onSubmit={handleAnalyze}>
          <label htmlFor="url">Website URL</label>
          <div className="input-row">
            <input id="url" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://example.com" />
            <button className="primary-btn" disabled={loading || !url.trim()}>
              {loading ? "Analyzing..." : "Analyze"}
            </button>
          </div>
        </form>
        {error && <div className="error-box">{error}</div>}
      </section>

      {loading && <LoadingCard />}
      {analysis && <AnalysisReport analysis={analysis} />}
    </div>
  );
}

function AnalysisReport({ analysis }: { analysis: Analysis }) {
  return (
    <div className="report-stack">
      <div className="report-top">
        <section className="panel score-panel">
          <div className="score-ring" style={{ "--score": analysis.performanceScore } as React.CSSProperties}>
            <div><strong>{analysis.performanceScore}</strong><span>/100</span></div>
          </div>
          <div>
            <div className="eyebrow">Overall performance</div>
            <h2>{scoreLabel(analysis.performanceScore)}</h2>
            <p>{analysis.url} · Demo analysis · {formatDate(analysis.createdAt)}</p>
          </div>
        </section>

        <section className="panel vitals-panel">
          <Metric label="LCP" value={`${analysis.lcp.toFixed(1)}s`} good={analysis.lcp <= 2.5} />
          <Metric label="CLS" value={analysis.cls.toFixed(2)} good={analysis.cls <= 0.1} />
          <Metric label="INP" value={`${analysis.inp}ms`} good={analysis.inp <= 200} />
        </section>
      </div>

      <div className="score-grid">
        <ScoreCard title="Loading" score={analysis.loadingScore} />
        <ScoreCard title="Network" score={analysis.networkScore} />
        <ScoreCard title="Assets" score={analysis.assetScore} />
        <ScoreCard title="Rendering" score={analysis.renderingScore} />
        <ScoreCard title="Accessibility" score={analysis.accessibilityScore} />
      </div>

      <div className="two-col">
        <section className="panel">
          <div className="panel-head"><div><h3>API performance</h3><span>Endpoint-level demo telemetry</span></div></div>
          <div className="table-wrap">
            <table>
              <thead><tr><th>Endpoint</th><th>Latency</th><th>Status</th><th>Errors</th></tr></thead>
              <tbody>
                {analysis.apiMetrics.map((api) => (
                  <tr key={api.endpoint}>
                    <td><strong>{api.endpoint}</strong></td>
                    <td>{api.responseTime}ms</td>
                    <td><span className={`status-badge ${api.statusCode < 400 ? "ok" : "bad"}`}>{api.statusCode}</span></td>
                    <td>{api.errors}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section className="panel">
          <div className="panel-head"><div><h3>Asset audit</h3><span>Largest resources first</span></div></div>
          <div className="asset-list">
            {analysis.assets.map((asset) => (
              <div className="asset-row" key={asset.name}>
                <div><strong>{asset.name}</strong><span>{asset.type}</span></div>
                <b>{asset.sizeKb} KB</b>
                <span className={`status-badge ${asset.status === "good" ? "ok" : asset.status === "warning" ? "warn" : "bad"}`}>{asset.status}</span>
              </div>
            ))}
          </div>
        </section>
      </div>

      <section className="panel">
        <div className="panel-head"><div><h3>Optimization recommendations</h3><span>Generated by transparent rules</span></div></div>
        <div className="recommendation-grid">
          {analysis.recommendations.map((r, i) => (
            <div className="recommendation" key={`${r.title}-${i}`}>
              <div className={`rec-icon ${severityClass(r.severity)}`}><Sparkles size={16} /></div>
              <div>
                <div className="rec-head"><strong>{r.title}</strong><span className={`severity ${severityClass(r.severity)}`}>{r.severity}</span></div>
                <p>{r.problem}</p>
                <small><b>Suggested action:</b> {r.action}</small>
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}

function HistoryPage() {
  const [analyses, setAnalyses] = useState<Analysis[]>([]);
  const [query, setQuery] = useState("");

  useEffect(() => {
    getAnalyses().then(setAnalyses).catch(() => setAnalyses([]));
  }, []);

  const filtered = useMemo(() => analyses.filter((a) => a.url.toLowerCase().includes(query.toLowerCase())), [analyses, query]);

  return (
    <div className="page">
      <PageHeader eyebrow="Reports" title="Performance history" description="Review previous demo reports and identify trends." />
      <section className="panel">
        <div className="toolbar">
          <div className="search-input"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Filter by URL..." /></div>
          <Link className="primary-btn" to="/analyze">New analysis</Link>
        </div>
        {filtered.length === 0 ? <EmptyState /> : (
          <div className="table-wrap">
            <table>
              <thead><tr><th>URL</th><th>Score</th><th>LCP</th><th>CLS</th><th>INP</th><th>Bundle</th><th>Date</th></tr></thead>
              <tbody>
                {filtered.map((a) => (
                  <tr key={a.id}>
                    <td><strong>{a.url}</strong><small>Demo mode</small></td>
                    <td><ScoreBadge score={a.performanceScore} /></td>
                    <td>{a.lcp.toFixed(1)}s</td><td>{a.cls.toFixed(2)}</td><td>{a.inp}ms</td>
                    <td>{a.bundleSize} KB</td><td>{formatDate(a.createdAt)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </div>
  );
}

function ComparePage() {
  const [analyses, setAnalyses] = useState<Analysis[]>([]);
  const [before, setBefore] = useState("");
  const [after, setAfter] = useState("");

  useEffect(() => {
    getAnalyses().then((data) => {
      setAnalyses(data);
      if (data.length >= 2) {
        setBefore(data[1].id);
        setAfter(data[0].id);
      }
    }).catch(() => setAnalyses([]));
  }, []);

  const b = analyses.find((a) => a.id === before);
  const a = analyses.find((x) => x.id === after);

  const rows = b && a ? [
    ["Performance score", b.performanceScore, a.performanceScore, false],
    ["LCP (seconds)", b.lcp, a.lcp, true],
    ["CLS", b.cls, a.cls, true],
    ["INP (ms)", b.inp, a.inp, true],
    ["Bundle size (KB)", b.bundleSize, a.bundleSize, true],
    ["API latency (ms)", b.apiResponseTime, a.apiResponseTime, true],
    ["Requests", b.requestCount, a.requestCount, true]
  ] : [];

  return (
    <div className="page">
      <PageHeader eyebrow="Optimization" title="Compare reports" description="Compare two analyses to quantify performance changes." />
      <section className="panel">
        <div className="compare-selects">
          <label>Before<select value={before} onChange={(e) => setBefore(e.target.value)}><option value="">Select report</option>{analyses.map((x) => <option key={x.id} value={x.id}>{x.url} · {formatDate(x.createdAt)}</option>)}</select></label>
          <GitCompare className="compare-icon" />
          <label>After<select value={after} onChange={(e) => setAfter(e.target.value)}><option value="">Select report</option>{analyses.map((x) => <option key={x.id} value={x.id}>{x.url} · {formatDate(x.createdAt)}</option>)}</select></label>
        </div>
      </section>
      {b && a ? (
        <section className="panel">
          <div className="table-wrap">
            <table>
              <thead><tr><th>Metric</th><th>Before</th><th>After</th><th>Change</th></tr></thead>
              <tbody>
                {rows.map(([name, bv, av, lower]) => {
                  const change = lower ? ((Number(bv) - Number(av)) / Number(bv)) * 100 : ((Number(av) - Number(bv)) / Number(bv)) * 100;
                  const positive = change >= 0;
                  return <tr key={String(name)}><td><strong>{String(name)}</strong></td><td>{Number(bv).toFixed(typeof bv === "number" && Number(bv) < 10 ? 2 : 0)}</td><td>{Number(av).toFixed(typeof av === "number" && Number(av) < 10 ? 2 : 0)}</td><td><span className={`change ${positive ? "positive" : "negative"}`}>{positive ? "+" : ""}{change.toFixed(1)}%</span></td></tr>;
                })}
              </tbody>
            </table>
          </div>
        </section>
      ) : <EmptyState title="Create at least two analyses" description="Run two reports from New Analysis to unlock the comparison view." />}
    </div>
  );
}

function Architecture() {
  return (
    <div className="page">
      <PageHeader eyebrow="Engineering" title="System architecture" description="A simple view of how the frontend, API and analysis engine communicate." />
      <section className="panel architecture">
        <ArchitectureNode title="React + TypeScript" subtitle="UI / routing / state / charts" />
        <div className="flow-line" />
        <ArchitectureNode title="Express REST API" subtitle="Validation / business logic / HTTP" />
        <div className="flow-line" />
        <ArchitectureNode title="Deterministic Analysis Engine" subtitle="Scoring / recommendations / demo telemetry" />
        <div className="flow-line" />
        <ArchitectureNode title="MongoDB" subtitle="Persistent analysis reports" />
      </section>
      <div className="two-col">
        <section className="panel"><h3>Why this architecture?</h3><p className="long-copy">The frontend is separated from backend services so UI concerns remain independent from analysis and persistence. REST endpoints provide a predictable contract, while the analysis engine keeps scoring rules explainable and testable.</p></section>
        <section className="panel"><h3>Production upgrade path</h3><p className="long-copy">A production version could connect a controlled browser worker such as Lighthouse/Playwright for real measurements, add authentication, queue analysis jobs, cache reports, and stream progress updates to the frontend.</p></section>
      </div>
    </div>
  );
}

function SettingsPage() {
  const [notifications, setNotifications] = useState(false);
  async function enableNotifications() {
    if (!("Notification" in window)) return;
    const permission = await Notification.requestPermission();
    setNotifications(permission === "granted");
  }
  return (
    <div className="page">
      <PageHeader eyebrow="Preferences" title="Settings" description="Configure local demo preferences." />
      <section className="panel settings">
        <div className="setting-row">
          <div><strong>Browser notifications</strong><p>Allow critical demo recommendations to trigger a browser notification.</p></div>
          <button className="secondary-btn" onClick={enableNotifications}>{notifications ? "Enabled" : "Enable"}</button>
        </div>
        <div className="setting-row">
          <div><strong>Demo mode</strong><p>Demo mode is always enabled in this portfolio version so the application remains reliable without crawling external sites.</p></div>
          <span className="status-badge ok">Active</span>
        </div>
      </section>
    </div>
  );
}

function StatCard({ icon, label, value, meta }: { icon: React.ReactNode; label: string; value: string; meta: string }) {
  return <div className="stat-card"><div className="stat-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{meta}</small></div>;
}

function ScoreBadge({ score }: { score: number }) {
  return <span className={`score-badge ${score >= 90 ? "good" : score >= 75 ? "warn" : "bad"}`}>{score}</span>;
}

function StatusRow({ label, status, ok }: { label: string; status: string; ok: boolean }) {
  return <div className="status-row"><div><span className={`status-dot ${ok ? "ok" : "bad"}`} />{label}</div><strong>{status}</strong></div>;
}

function Metric({ label, value, good }: { label: string; value: string; good: boolean }) {
  return <div className="metric"><span>{label}</span><strong>{value}</strong><small className={good ? "good-text" : "bad-text"}>{good ? "Good" : "Needs attention"}</small></div>;
}

function ScoreCard({ title, score }: { title: string; score: number }) {
  return <div className="mini-score"><div><span>{title}</span><strong>{score}</strong></div><div className="progress"><span style={{ width: `${score}%` }} /></div></div>;
}

function EmptyState({ title = "No reports yet", description = "Run your first analysis to populate this workspace." }: { title?: string; description?: string }) {
  return <div className="empty"><Gauge size={28} /><h3>{title}</h3><p>{description}</p><Link className="primary-btn" to="/analyze">Run analysis</Link></div>;
}

function LoadingCard() {
  return <section className="panel loading-card"><div className="spinner" /><h3>Running analysis engine...</h3><p>Calculating loading, network, asset and rendering signals.</p></section>;
}

function ArchitectureNode({ title, subtitle }: { title: string; subtitle: string }) {
  return <div className="architecture-node"><div className="node-icon"><Terminal size={20} /></div><div><strong>{title}</strong><span>{subtitle}</span></div></div>;
}

function NotFound() {
  const navigate = useNavigate();
  return <div className="page"><div className="empty"><h2>Page not found</h2><button className="primary-btn" onClick={() => navigate("/")}>Back to overview</button></div></div>;
}

export default App;